# Individual Project 2
## Caitlin Sizemore 
### DS 160-01 Spring 2023 
### Version 1

In [1]:
import numpy as np

In [12]:
a=np.array([(10, 20), (30, 40)])
a

array([[10, 20],
       [30, 40]])

In [13]:
np.square(a)

array([[ 100,  400],
       [ 900, 1600]])

In [14]:
a+100

array([[110, 120],
       [130, 140]])

In [15]:
a*5

array([[ 50, 100],
       [150, 200]])

In [16]:
np.sqrt(a)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [23]:
b=np.arange(3,28,3)
b.resize(3,3)
b

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [25]:
c=np.linspace(10,20,9)
c.resize(3,3)
c

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [26]:
b*c

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

In [29]:
d=np.load('process1.npy')
e=np.load('process2.npy')
f=np.load('process3.npy')
g=np.load('process4.npy')
h=np.load('process5.npy')

In [30]:
array1=np.vstack([d,e,f,g,h])
array1

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [31]:
np.mean(array1, axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])